version = "GSAP01-DEBUG"
version_num = 0
cflags = [
    "-nodefaults",
    "-proc",
    "gekko",
    "-align",
    "powerpc",
    "-enum",
    "int",
    "-fp",
    "hardware",
    "-Cpp_exceptions",
    "off",
    # "-W all",
    # "-O4,p",
    # "-O1,p",
    "-O0",
    "-opt",
    "peephole",
    # "-opt off",
    "-g",
    # "-func_align 8",
    # "-common on",
    # "-inline auto",
    # "-inline noauto,deferred",
    "-use_lmw_stmw",
    "on",
    "-pragma",
    '"cats off"',
    "-pragma",
    '"warn_notinlined off"',
    "-maxerrors",
    "1",
    "-nosyspath",
    "-RTTI",
    "off",
    "-fp_contract",
    "on",
    "-str",
    "reuse",
    "-multibyte",  # For Wii compilers, replace with `-enc SJIS`
    "-i",
    "include",
    "-i",
    "include/libc",
    "-i",
    f"build/{version}/include",
    f"-DVERSION={version_num}",
]
